plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/jaikharbanda/Library/Mobile Documents/com~apple~CloudDocs/Essentials/Claude Code/jaikharbanda-xyz/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "https://www.jaikharbanda.xyz/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]